#cloud-config
# Refresh the locally cached package listing from the network repository
repo_update: true
# apply security upgrades, which is the default anyway
# see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#security-updates
repo_upgrade: security

runcmd:
  - apt-get install -y curl
  # install for the ubuntu user
  - curl -fsSL https://raw.githubusercontent.com/tekumara/setup-nvidia/main/install.sh | bash -s
