name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: install.sh
        run: ./install.sh

      - name: Start sshx session on failed manual run or retry
        if: ${{ failure() && (github.event_name == 'workflow_dispatch' || github.run_attempt > 1) }}
        run: curl -sSf https://sshx.io/get | sh && sshx
